### ISSUE TITLE
Add domain for "now" deplyoments to CORS-Rules

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli.github.io#100]
As a developer/reviewer i would like to see a online preview of a PR that behaves like the normal deployed website. Therefore the content from remote pages (consol.de / consol.com) have to be loaded without CORS-issues.

** Additional Information **

PRs are deployed on [https://zeit.co/home]. With the following url schema: `https://[PR-TITLE].s1hofmann.now.sh/`. To allow this pages to load contents from consol.com a cors rul have to be added on consol.com. the rule should allow all request from `*.s1hofmann.now.sh`.

Additionally we could think about a wildcard for something like `*.sakuli.now.sh/`  or `*.sakuli-io.now.sh/` when we create a dedicated sakuli account on zeit.co for sakuli.

**Comment by ZNicoZ** [comment]
Requested cors enhancement at Consol

**Comment by ZNicoZ** [comment]
*.s1hofmann.now.sh added to CORS 

![image.png](https://images.zenhubusercontent.com/5d9af7992558c40001a2d43b/64903c35-4f96-4248-954f-03fe3efcb994)

**Comment by tnobody** [comment]
Can also confirm for https://sakuligithubio-git-develop.s1hofmann.now.sh/enterprise

So I'll move this issue to done.

**Comment by tnobody** [comment]
Since our page repor doesn't follow the realease cycle of sakuli I move this issue to `closed` and close it.
