### ISSUE TITLE
Instances clarification

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli.github.io#104]
As a customer I want to have an easy overview about the Enterprise offers. 
At the moment Instances are limited by <4 etc. - we should change this just to "4" etc., except for XL package, it should say "individual"

This will add one instance per package but will look consistent an is easy to read / comprehend.

**Comment by tnobody** [comment]
This issue is actually done, right? Because I see the new "labels" at sakuli.io
Wasn't there any PR or commit 🤔  😨

**Comment by ZNicoZ** [comment]
Yes it's done, I pushed the changes directly to develop as it was only text change.
