### ISSUE TITLE
Optimize Header Logo Image

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli.github.io#12]
- ~~Update format to .svg~~
- on screen-size lower than 820px only the icon should be shown

**Comment by ZNicoZ** [comment]
#13

**Comment by tnobody** [comment]
Is it intended that the updated logo is always "small"?

**Comment by ZNicoZ** [comment]
Don't know exactly what you mean, but do with it whatever you like :)

**Comment by ZNicoZ** [comment]
I now understand what you mean.
It would be nice to have the full sakuli logo 
![image](https://user-images.githubusercontent.com/7655980/58866774-93e76d00-86b9-11e9-8652-4b60b469ec58.png)
at first and while scrolling it turns into this one
![image](https://user-images.githubusercontent.com/7655980/58866836-ab265a80-86b9-11e9-81a9-249de5e562fd.png)
