### ISSUE TITLE
www.sakuli.io delivers cert error

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli.github.io#120]
https://www.sakuli.io/ delivers a cert error, while https://sakuli.io/ works fine.

Acceptance criteria:
- [ ] https://www.sakuli.io/ is working
- [ ] https://sakuli.io/ is still working

**Comment by ZNicoZ** [comment]
It seems for now the only solution would be to switch to another host, as github pages with let´s encrypt does not support this:

https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116

**Comment by svettwer** [comment]
Worked for them: https://stackoverflow.com/a/9123911/1889928

**Comment by svettwer** [comment]
Nevermind. Nobody beside me ever got this issue as it seems
