### ISSUE TITLE
Data privacy content from consol.de

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli.github.io#26]
A click on the "data privacy" link should not redirect to consol.de domain but should rather fetch the content of https://www.consol.com/data-privacy/ and render it in an overlay.
This ensures consistency to consol compliance.

**Comment by tnobody** [comment]
After thinking about it, I see a threat with this.
I'm not sure about the legal regulation on this topic but putting this content in a modal makes it not accessible for users which turned of javascript. AFAIK such content have to be accessible. As a "quick win" we can use progressive enhancement, so the link will behave will go to consol.de when js is turned off?!

**Comment by ZNicoZ** [comment]
Ok, good point - and perfect solution!
