### ISSUE TITLE
Enterprise contact

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli.github.io#27]
Form of https://www.consol.de/anfrage-sakuli-enterprise should be fetched and rendered within sakuli.io. Adapt CSS and labels. Pre-Select package according to user-selection. 
After form submit, don´t redirect to consol.de but show a thank you notification on sakuli.io.

**Comment by tnobody** [comment]
should we show the form in an overlay/modal?

**Comment by ZNicoZ** [comment]
That would be nice, yes.
