### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli.github.io#28]
Let´s encrypt certificate needs to be implemented and activated.

**Comment by s1hofmann** [comment]
> Not yet available for your site because the certificate has not finished being issued. Please allow 24 hours for this process to complete. (sakuli.io) 

Looks like there's already a cert in the making. Will check back later for updates.

**Comment by s1hofmann** [comment]
Done, [sakuli.io](https://sakuli.io) is served via https
