### ISSUE TITLE
Add documentation for typescript support

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli.github.io#92]
As a user I want to have a guide to enable typescript support to know how to setup Sakuli and IDE in order to use typescript.

**Additional Information**

- We should introduce a new section `Tooling` in the documentation pages and add the a article about Typescript support
- Contents should be:
  - Using the `enable-typescript` commad
  - Setting up VS-Code

**Comment by svettwer** [comment]
See: https://sakuli.io/docs/writing_tests/tutorial/#typescript
