### ISSUE TITLE
Add "Request Demo Licence" to sakuli.io/enterprise/

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli.github.io#97]
As a potential Sakuli enterprise user, I want to request a 14 days trial Sakuli enterprise licence via the "Request Demo From" on https://sakuli.io/enterprise/, so that I can test the product on my own.

**Additional Information**
In the first attempt, it would be enough to add a "Request demo licence" to the drop down box of the form.

**Comment by ZNicoZ** [comment]
Requested changes at fetch origin.

**Comment by tnobody** [comment]
information and free-demo option is already shown in the form. Can we close this ticket?
